---
# Exercise for setting up a web server in an EC
- name: Exercise for setting up a web server in an EC
    # hosts: ubuntu
  # Use the public IP if the VM is already created
  hosts: 54.235.16.227
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
    - setup